spring:
  application:
    name: 37-SBMS-Welcome-API
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'